### ISSUE TITLE
Merge sound

### ISSUE THREAD

**Issue by fariki** [umair13adil/KotlinFFMpeg#1]
How to combine sound with a video file with original audio video? Or how combine two sound?

**Comment by umair13adil** [comment]
Here is the command to merge two audio files:

` val cmd = arrayOf("-y", "-i", audio1!!.path, "-i", audio2!!.path, "-filter_complex", "amix=inputs=2:duration=first:dropout_transition=0", "-codec:a", "libmp3lame", "-q:a", "0", outputLocation.path)
`

You can find this implementation in latest commit : [AudioMerger](https://github.com/umair13adil/KotlinFFMpeg/commit/477a68841312f1bb3116587c750726fccf4b3b4e)
