### ISSUE TITLE
ffmpeg binary

### ISSUE THREAD

**Issue by thematrixdev** [umair13adil/KotlinFFMpeg#15]
Hello,

May I know if I need to place the FFMPEG binary file somewhere before I can use your code? Or, putting the two lines on Gradle does the work?

Thanks.

**Comment by umair13adil** [comment]
Hi,

You just need to add these 2 lines to gradle file:

      implementation 'com.writingminds:FFmpegAndroid:0.3.2'

      implementation 'org.jcodec:jcodec-android:0.1.9'
