### ISSUE TITLE
How to convert video to MPEG-4, Format profile: Base Media / Version 2

### ISSUE THREAD

**Issue by kasim1011** [umair13adil/KotlinFFMpeg#4]
I'm using `VideoResizer`. The output video is 

	Format                      : MPEG-4
	Format profile              : Base Media
	Codec ID                    : isom (isom/iso2/avc1/mp41)

What I want is

	Format                      : MPEG-4
	Format profile              : Base Media / Version 2
	Codec ID                    : mp42 (mp41/mp42/isom)

current `cmd` is https://github.com/umair13adil/KotlinFFMpeg/blob/5612e29f3f05bec08263e6cba6b172962b06912e/app/src/main/java/com/blackbox/ffmpeg/examples/tools/video/VideoResizer.kt#L63
 
I've tried using (reference [8.5.2 Examples](https://ffmpeg.org/ffmpeg-codecs.html#Examples))

    val cmd = arrayOf("-i", video!!.path, "-c:a", "libfdk_aac", "-profile:a", "aac_he", "-b:a", "64k", "scale=" + size, outputLocation.path) /*, "-hide_banner"*/

I've got following error

	java.io.IOException: ffmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers
		  built with gcc 4.8 (GCC)
		  configuration: --target-os=linux --cross-prefix=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-pthreads --disable-debug --disable-ffserver --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-ffprobe --enable-gpl --enable-yasm --disable-doc --disable-shared --enable-static --pkg-config=/home/vagrant/SourceCode/ffmpeg-android/ffmpeg-pkg-config --prefix=/home/vagrant/SourceCode/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/home/vagrant/SourceCode/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-libs='-lpng -lexpat -lm' --extra-cxxflags=
		  libavutil      55. 17.103 / 55. 17.103
		  libavcodec     57. 24.102 / 57. 24.102
		  libavformat    57. 25.100 / 57. 25.100
		  libavdevice    57.  0.101 / 57.  0.101
		  libavfilter     6. 31.100 /  6. 31.100
		  libswscale      4.  0.100 /  4.  0.100
		  libswresample   2.  0.101 /  2.  0.101
		  libpostproc    54.  0.100 / 54.  0.100
		Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/storage/emulated/0/DCIM/Camera/20180731_115412.mp4':
		  Metadata:
	07-31 16:30:18.049 17290-17290/com.riglynx.riglynx.test W/System.err:     major_brand     : mp42
			minor_version   : 0
			compatible_brands: isommp42
			creation_time   : 2018-07-31 06:24:19
			location        : +23.0260+072.5079/
			location-eng    : +23.0260+072.5079/
			com.android.version: 7.0
		  Duration: 00:00:05.63, start: 0.000000, bitrate: 17341 kb/s
			Stream #0:0(eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 17051 kb/s, SAR 1:1 DAR 16:9, 29.98 fps, 30 tbr, 90k tbn, 180k tbc (default)
			Metadata:
			  rotate          : 90
			  creation_time   : 2018-07-31 06:24:19
			  handler_name    : VideoHandle
			Side data:
			  displaymatrix: rotation of -90.00 degrees
			Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
			Metadata:
			  creation_time   : 2018-07-31 06:24:19
			  handler_name    : SoundHandle
		[NULL @ 0xf052f600] Unable to find a suitable output format for 'scale=720:1280'
		scale=720:1280: Invalid argument

How can I get my desire output

Thanks.

**Comment by umair13adil** [comment]
I think this example [8.5.2 Examples](https://ffmpeg.org/ffmpeg-codecs.html#Examples) requires you to input audio file's path, and you are providing it video file's path. It says 

> Use ffmpeg to convert an audio file to CBR 64k kbps AAC, using the High-Efficiency AAC profile

`"-i", video!!.path`

try same example with audio file's path.

**Comment by kasim1011** [comment]
I found solution from [here](https://stackoverflow.com/a/43607479/3702021)

    "-i", video!!.path, "-vf", "scale=" + size, "-brand", "mp42", outputLocation.path

Output video is:

	Format                      : MPEG-4
	Format profile              : Base Media / Version 2
	Codec ID                    : mp42 (isom/iso2/avc1/mp41)
